branches:
  only:
    - master

sudo: required

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1 --no-include-email)

script:
  - docker --version
  - docker build -t vassist .
  - docker tag vassist:latest 902382300595.dkr.ecr.us-east-1.amazonaws.com/vassist:latest
  - docker push 902382300595.dkr.ecr.us-east-1.amazonaws.com/vassist:latest
